# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: Ec2pool

parameters:
  - name: push
    displayName: push
    type: boolean
    default: false
  - name: StampName
    displayName: StampName
    default: azuredevopspractice
    type: string
    values:
      - azuredevopspractice
      - test

steps:

- template: yaml/docker_build_push.yml
  parameters:
    push: ${{ parameters.push }}
    stampName: ${{ parameters.stampName }}
    repository: ${{ last(split(variables['Build.Repository.Name'], '/')) }}